Comp doctores
davidlondonor/Citaclic-frontend pull request #3
Opened 2019-11-04 22:13 UTC by davidlondonor

Realicé la actualización.
los componententes tienen unas cajitas pintadas pero es para que lo miremos antes de lanzarlo, mas por visualizacion del inspector!

2019-11-05 01:38 UTC, leocabeza commented on src/App.js
> +        <Route exact path='/doctores' component={PageDoc} />
Bien!

2019-11-05 01:41 UTC, leocabeza commented on src/App.js
> +        <Route exact path='/Cards' component={Cards} />
3 cosas:
* Esta ruta no es necesaria
* El nombre "Cards" es muy genérico, ¿Cards?, ¿Tarjetas de que?
* Dentro del componente Cards, veo que importaste Footer y Menu, no es necesario que los importes, ya que en el App.js ya están definidos

2019-11-05 01:45 UTC, leocabeza commented on src/App.js
> +        <Route exact path='/doctores' component={PageDoc} />
Veo que la ruta es "doctores", pero se muestra solo el perfil de un Dr Aquí,
Creo que lo que se quiere es:
* Tener una ruta "/doctores" que muestre una lista de doctores, filtros y demás (Me parece que es el componente "Cards" que creaste)
* Tener una ruta "/doctores/:id" que muestre un doctor en específico, (Me parece que este debe ser el componente "PageDoc" que creaste).

Entonces cambiaría la línea 25 y 26 por:

<Route path ='/doctores' component={Cards}>
<Route path='/doctores/:id' component={PageDoc}

Si me explique o entendí algo mal, avisame @davidlondonor

2019-11-05 01:48 UTC, leocabeza commented
Como nota muy general y no es nada importante, sería bueno que cuando trabajen utilicen o comillas simples o dobles, pero no ambas. Y también que no suban código comentado que no están utilizando, por ej.:

```
.pagina {
  display: flex;
  // display: block;
}

```

o

```
const cuenta = () => {
  // return asd;
  return "1,2,3";
};
```

2019-11-05 04:06 UTC, davidlondonor commented on src/App.js
> +        <Route exact path='/doctores' component={PageDoc} />
Tienes razón en los dos puntos, 
```suggestion
        `<Route exact path='/doctores' component={PageDoc} />
          <Route exact path='/doctores/:id' component={PageDoc}/>` _así es_
``` **Consulta:** Yo Puedo cambiar la 25 por 26? creo que quedaría así, @DboraSoto

2019-11-05 04:06 UTC, davidlondonor commented on src/App.js
> +        <Route exact path='/Cards' component={Cards} />
Sí, de hecho nos queda como ingles español y se ve raro, yo creo que pueden ser _agendaMedica_ pensando en que será ruta y será className en React, en VsCode nos permite cambiarlo y se actualiza @DboraSoto que te parece o le pones otro nombre. 

Del footer y Menu, :+1:

2019-11-05 04:08 UTC, davidlondonor reviewed
Este es mi primer Comment desde acá, :smiley:

2019-11-06 14:01 UTC, leocabeza commented on src/pageDocs/Hour.jsx
> +class Hour extends Component {
Cuando tenemos un componente sin estado, es mejor utilizar un componente funcional. ej.:

```
const Hour = () => {
  return (
   <div>Componente funcional</div>
  );
};
```

2019-11-06 14:02 UTC, leocabeza commented on src/pageDocs/Day.jsx
> +class Day extends Component {
El mismo comentario de componentes funcionales

2019-11-06 14:03 UTC, leocabeza commented on src/pageDocs/Cards.jsx
> +    console.log(this.state);
Esto está bien hacerlo en desarrollo, pero no que quedé en producción, por lo cual sería bueno quitarlo

2019-11-06 14:03 UTC, leocabeza commented on src/pageDocs/Cards.jsx
> +    fetch("https://randomuser.me/api/?results=11")
Bien!

2019-11-06 14:05 UTC, leocabeza commented on src/App.js
> +import { Link } from "react-router-dom";
Esta línea no se puede eliminar ya que no se está utilizando el componente

2019-11-06 14:07 UTC, leocabeza commented on src/App.js
> +import Cards from "./pageDocs/Cards";
Te dejo el mismo comentari que la vez anterior, **Cards** no es un nombre descriptivo, quizás PerfilDoctor, o Doctor sería mejor. Debido a que _Cards_ y _Pagedoc_ son componentes totalmente distintos, tendrían que ir en carpetas distintas y no todo junto en _pageDocs_

2019-11-06 14:08 UTC, leocabeza requested changes
Te dejé algunos comentarios con respecto a los nuevos cambios y los viejos

2019-11-06 16:30 UTC, davidlondonor commented on src/pageDocs/Hour.jsx
> +class Hour extends Component {
De uuna! Débora me ayudó

2019-11-06 16:33 UTC, davidlondonor commented on src/pageDocs/Day.jsx
> +class Day extends Component {
DE una!!!

2019-11-06 16:36 UTC, davidlondonor commented on src/pageDocs/Cards.jsx
> +    console.log(this.state);
Listo! ya lo quitamos! y siguio funcionando

2019-11-06 16:41 UTC, davidlondonor commented on src/App.js
> +import { Link } from "react-router-dom";
Débora te va a consultar una cosa de esta línea!

2019-11-06 16:46 UTC, davidlondonor commented on src/App.js
> +import Cards from "./pageDocs/Cards";
De una! Súper bien el comentario

2019-11-06 18:04 UTC, leocabeza commented on src/App.js
> +        <Route exact path='/perfildoctores' component={perfilDoctores} />
¿Porqué borraste el /:id? 

Debería ser:
`<Route path='/perfildoctores/:id' component={perfilDoctores} />`

2019-11-07 14:27 UTC, leocabeza approved these changes

2019-11-07 14:27 UTC, merged